version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./client/.env.local
    ports:
      - "8182:80"
    networks:
      - app

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    networks:
      - app

networks:
  app: {}
